In [2]:
import tensorflow as tf
import numpy as np
import keras

from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import to_categorical

from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix

In [8]:
y_train = np.loadtxt("train_data/labels_actions.csv")
y_train=keras.utils.to_categorical(y_train,3)
print(y_train.shape)

y_test = np.loadtxt("test_data/labels_actions.csv")
y_test=keras.utils.to_categorical(y_test,3)
print(y_test.shape)

p_order = 10
filename = "AR_coef_p_order_{p_order}_with_RMS.csv".format(p_order = p_order)
X_train = np.loadtxt("train_data/"+filename, delimiter=',')
print(X_train.shape)

X_test = np.loadtxt("test_data/"+filename, delimiter=',')
print(X_test.shape)

(126, 3)
(27, 3)
(126, 33)
(27, 33)


In [4]:
model = Sequential() 
model.add(Dense(10, input_shape=(X_train.shape[1], ), activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                340       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 483
Trainable params: 483
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
4/4 [==============================] - 0s 84ms/step - loss: 1.1671 - accuracy: 0.3175 - val_loss: 1.0431 - val_accuracy: 0.4815
Epoch 2/100
4/4 [==============================] - 0s 18ms/step - loss: 1.1417 - accuracy: 0.3175 - val_loss: 1.0491 - val_accuracy: 0.4815
Epoch 3/100
4/4 [==============================] - 0s 14ms/step - loss: 1.1187 - accuracy: 0.3175 - val_loss

In [9]:
score = model.evaluate(X_test, y_test, verbose = 0) 
print('Test loss:', score[0]) 
print('Test accuracy:', score[1])

# test
pred = model.predict(X_test)
pred = np.argmax(pred, axis = 1) 
label = np.argmax(y_test,axis = 1)
cm = confusion_matrix(label, pred)
print(cm)

print("----")
acc = 0
rand_pred = np.random.randint(3, size=(27))
for i in range(len(pred)):
    if (rand_pred[i] == label[i]):
        acc += 1

acc /= 27
print("RANDOM ACC:", acc)

Test loss: 1.0270895957946777
Test accuracy: 0.4444444477558136
[[0 3 3]
 [2 4 2]
 [0 5 8]]
----
RANDOM ACC: 0.2222222222222222


In [10]:
# evaluate on validation set
y_val = np.loadtxt("validation_data/labels_actions.csv")
y_val = keras.utils.to_categorical(y_val,3)
print(y_val.shape)

filename = "AR_coef_p_order_{p_order}_with_RMS.csv".format(p_order = p_order)
X_val = np.loadtxt("validation_data/"+filename, delimiter=',')
print(X_val.shape)

score = model.evaluate(X_val, y_val, verbose = 0) 
print('Validation loss:', score[0]) 
print('Validation accuracy:', score[1])

(27, 3)
(27, 33)
Validation loss: 1.0677822828292847
Validation accuracy: 0.29629629850387573
